package dev.toastmc.toastclient.api.util

import org.lwjgl.glfw.GLFW

object KeyUtil {

    fun getKeyName(key: Int): String {
        return when (key) {
            GLFW.GLFW_KEY_UNKNOWN -> "NONE"
            GLFW.GLFW_KEY_ESCAPE -> "ESC"
            GLFW.GLFW_KEY_PRINT_SCREEN -> "PRINT"
            GLFW.GLFW_KEY_PAUSE -> "PAUSE"
            GLFW.GLFW_KEY_INSERT -> "INSERT"
            GLFW.GLFW_KEY_DELETE -> "DELETE"
            GLFW.GLFW_KEY_HOME -> "HOME"
            GLFW.GLFW_KEY_PAGE_UP -> "PAGE UP"
            GLFW.GLFW_KEY_PAGE_DOWN -> "PAGE DOWN"
            GLFW.GLFW_KEY_END -> "END"
            GLFW.GLFW_KEY_TAB -> "TAB"
            GLFW.GLFW_KEY_LEFT_CONTROL -> "LCTRL"
            GLFW.GLFW_KEY_RIGHT_CONTROL -> "RCTRL"
            GLFW.GLFW_KEY_LEFT_ALT -> "LALT"
            GLFW.GLFW_KEY_RIGHT_ALT -> "RALT"
            GLFW.GLFW_KEY_LEFT_SHIFT -> "LSHIFT"
            GLFW.GLFW_KEY_RIGHT_SHIFT -> "RSHIFT"
            GLFW.GLFW_KEY_UP -> "UP"
            GLFW.GLFW_KEY_DOWN -> "DOWN"
            GLFW.GLFW_KEY_LEFT -> "LEFT"
            GLFW.GLFW_KEY_RIGHT -> "RIGHT"
            GLFW.GLFW_KEY_APOSTROPHE -> "APOSTROPHE"
            GLFW.GLFW_KEY_BACKSPACE -> "BACKSPACE"
            GLFW.GLFW_KEY_CAPS_LOCK -> "CAPSLOCK"
            GLFW.GLFW_KEY_MENU -> "MENU"
            GLFW.GLFW_KEY_LEFT_SUPER -> "LSUPER"
            GLFW.GLFW_KEY_RIGHT_SUPER -> "RSUPER"
            GLFW.GLFW_KEY_ENTER -> "ENTER"
            GLFW.GLFW_KEY_NUM_LOCK -> "NUMLOCK"
            GLFW.GLFW_KEY_SPACE -> "SPACE"
            GLFW.GLFW_KEY_F1 -> "F1"
            GLFW.GLFW_KEY_F2 -> "F2"
            GLFW.GLFW_KEY_F3 -> "F3"
            GLFW.GLFW_KEY_F4 -> "F4"
            GLFW.GLFW_KEY_F5 -> "F5"
            GLFW.GLFW_KEY_F6 -> "F6"
            GLFW.GLFW_KEY_F7 -> "F7"
            GLFW.GLFW_KEY_F8 -> "F8"
            GLFW.GLFW_KEY_F9 -> "F9"
            GLFW.GLFW_KEY_F10 -> "F10"
            GLFW.GLFW_KEY_F11 -> "F11"
            GLFW.GLFW_KEY_F12 -> "F12"
            GLFW.GLFW_KEY_F13 -> "F13"
            GLFW.GLFW_KEY_F14 -> "F14"
            GLFW.GLFW_KEY_F15 -> "F15"
            GLFW.GLFW_KEY_F16 -> "F16"
            GLFW.GLFW_KEY_F17 -> "F17"
            GLFW.GLFW_KEY_F18 -> "F18"
            GLFW.GLFW_KEY_F19 -> "F19"
            GLFW.GLFW_KEY_F20 -> "F20"
            GLFW.GLFW_KEY_F21 -> "F21"
            GLFW.GLFW_KEY_F22 -> "F22"
            GLFW.GLFW_KEY_F23 -> "F23"
            GLFW.GLFW_KEY_F24 -> "F24"
            GLFW.GLFW_KEY_F25 -> "F25"
            else -> (GLFW.glfwGetKeyName(key, -1) ?: return "NONE").toUpperCase()
        }
    }
}
