name: Build and Upload to Discord

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD: ${{ github.run_number }}
      SHA: ${{ github.sha }}
      WEBHOOK: ${{ secrets.BUILD_WEBHOOK }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Rename the built jar
        run: mv build/libs/toastclient-2.1.jar toastclient-$BUILD.jar
      - name: Test vars
        run: echo $BUILD && echo " " && echo $SHA
      - name: Send Discord build message
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"Build number $BUILD from commit $SHA:\"}" $WEBHOOK
      - name: Upload client jar
        run: curl -F data=@toastclient-$BUILD.jar $WEBHOOK