name: Build and Upload Development Artifact to Discord

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD: ${{ github.run_number }}
      SHA: ${{ github.sha }}
      WEBHOOK: ${{ secrets.BUILD_DISCORD_WEBHOOK }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Rename the built jar
        run: mv build/libs/toastclient-2.1.jar toastclient-${{ github.run_number }}.jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: toastclient-${{ github.run_number }}
          path: toastclient-${{ github.run_number }}.jar
      - uses: nelonoel/branch-name@v1.0.1
      - name: Send Discord build message
        run: |
          COMMITMESSAGE="$(git log --pretty=format:'- \`%h\` %s\n' -1 --reverse)" &&
          (curl "$WEBHOOK" -H "Content-Type:application/json" -X POST --data-raw '
          {
          	"content": null,
          	"embeds": [
          		{
          			"title": "Build '$BUILD'",
          			"description": "**Branch:** '$BRANCH_NAME'\n**Changes:**\n'$COMMITMESSAGE'",
          			"url": "'$GITHUB_SERVER_URL'/'$GITHUB_REPOSITORY'/actions/runs/'$GITHUB_RUN_ID'",
          			"color": 1487872,
          			"fields": [
          				{
          					"name": "Artifacts:",
          					"value": "- [toastclient-'$BUILD'.zip](https://nightly.link/'$GITHUB_REPOSITORY'/workflows/gradle.yaml/'$BRANCH_NAME'/toastclient-'$BUILD'.zip)"
          				}
          			],
          			"footer": {
          				"text": "'$GITHUB_REPOSITORY'"
          			},
          			"thumbnail": {
          				"url":"https://www.2b2t.com.au/assets/toast.png"
          			}
          		}
          	]
          }
          ')