name: Build and Upload to Discord

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD: ${{ github.run_number }}
      SHA: ${{ github.sha }}
      WEBHOOK: ${{ secrets.BUILD_DISCORD_WEBHOOK }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Rename the built jar
        run: mv build/libs/toastclient-2.1.jar toastclient-$BUILD.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: toastclient-$BUILD
          path: toastclient-$BUILD.jar
      - name: Send Discord build message
        run: |
          COMMITMESSAGE=`git log --pretty=format:'-\`%h\` %s' -5 --reverse` &&
          curl -H "Content-Type:application/json" -X POST -d "{\"content\":null,\"embeds\":[{\"title\":\"toastclient-$BUILD.jar\",\"url\":\"https://github.com/RemainingToast/ToastClient\",\"color\":1487872,\"fields\":[{\"name\":\"Changes:\",\"value\":\"$COMMITMESSAGE\"},{\"name\":\"Artifact:\",\"value\":\"- [toastclient-$BUILD.jar]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)\"}]}],\"username\":\"Dev Builds\"}" $WEBHOOK
